if: tag IS blank

env:
    - secure: "Pgsru9+3WGPHzZ19PTLHl1UnM19EvX2BE1KccExPUc4hnqTNub0cFB05dPyK0I7NuTmmJ+mejLfSnKEK0XSMbntLL/3LdNt3nYuOIleQdzPxv9KBRaS1mMp3c71lshhezq0jYe/8lF5M4MZqSka0dT/xSs3j3AXBpd/tJzUEX0NQGnb3ZxHFg+K2bMrh7dJ6Umazdz7Gs5WSIe+u/TN3EcDfH+5D4JCT+JFHPRs4HIMx7WhIG+Um18C9o/Texr9GpxItDQvCK9JIW/caqy8MfxcU/RGDosob6+LcO030W8RB1eEJXSWiVFIQKM7yo8pkTWf6RD0DWPV8x3lWRzNV5rnuJm/iWRPBruKE91MkZe3T/IJCnkh0UwhzBctQwv+oijNxKVEkUvbj+LX82O+lTHfK3G4VvVKw/VZWcM8k00Rvha/F2W3FfrmXo7fTDZ+sXD0Jnk+4CTEG+ZnrF2pChdfE78WgodZ9XxzhrTfEn6zwkz4qirBv0GdYTrt+9YiCQqMkyibrRApCFjU3+VH8z1vVu4kXi2M65mGQ0o+vzGGMCi49gRRanYkItUQ812ZPwGsSXolhEY+WEDeoQZ4GdR/kPjOtKrma6CJscapfU6P0mRrtNtXovMR0W7GUCGJZ3AZFSjdvMWnA+HNQBOJvkXEwUrer8kEKACq/gZCXpjc="

language: node_js

node_js:
    - "10"

os:
    - linux

cache: yarn

sudo: false
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
    - export PATH=$HOME/.yarn/bin:$PATH

script:
    - yarn run prettier:check
    - yarn run test:coverage
    - yarn run build

before_deploy:
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

# When a commit lands in master attempt to publish our packages.
deploy:
    provider: script
    skip_cleanup: true
    script:
        - |
        for f in ./packages/*; do ([ -d $$f ] && \
        cd $$f && \
        yarn publish --non-interactive --no-git-tag-version --no-commit-hooks | exit 0 && \
        done;
    on:
        branch: master

tags: true
