if: tag IS blank

env:
    - secure: "rOT/95niw4VZAcfLA0OssAb6Bb4VzCy/2vf7JPoJsTbkWzxKw72YDxkx/xDlOApgBbRDiWar9lW21ibyhsGBCQr0kyROTQ58V7oad0AXD3ut9KvtkHoXoCxXRJIrbt8Ajhl4pMTiDBSRbFPCErbjM15GXwAU5tcW0XGmGa7y8ysyEorl5aB+1AjhXw+F2vEqBM8xVxqwBvXnLFjVO6q6lFgb7dqdvqwH4WAoLC6b2sP7v3CNhLrPL5b7NTgs6WZFfRt1EiyoLVnnThuBOZpxENNOdx9dv8pEkFdljTOpwFxJgINhIJ7WOYK2N4U7sfB/WXJHjEk5PZ4SivZbDsIqRPd3B6F+mGRQsJKIQ633eIbYGp/5JHdpyyF8kAFM0yXR7MoSAnwu0tledNwnFoQ2XA+tIBdzATohF1NY+iL1IWkuNeuB7wk5QTujvrz5owSWoqsGq4pBO83zFrYvml4xNomH5vpsrqhy/GXjAdKzbpq5CmOrA7nWQ7iCotLj/zFEN07ihhJKqQwrCq1vUlK1eP9Mn0YFAlpS4LzC7B6Ssh4/ZLnosRfdime8P/EtyGutjZmQuP+Vp475WKt+EsRRKMx5uQwbSZ3p+Rr29My43VcIwKhI5hJb9kaHxLFK3HH9NQU4NaZEN7hpD1tBls5kV5OpIrqTVwKMkvOvls36Joc="

language: node_js

node_js:
    - "10"

os:
    - linux

cache: yarn

sudo: false
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
    - export PATH=$HOME/.yarn/bin:$PATH

script:
    - yarn run prettier:check
    - yarn run test:coverage
    - yarn run build

before_deploy:
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

# When a commit lands in master attempt to publish our packages.
deploy:
    provider: script
    skip_cleanup: true
    script:
        - yarn workspaces run publish --non-interactive --no-git-tag-version --no-commit-hooks
    on:
        branch: master

tags: true
